apiVersion: v1
kind: Pod
metadata:
  name: pubsub-publisher
  labels:
    app: web
spec:
  volumes:
    - name: credential
      secret:
        secretName: pubsub-credential
  containers:
    - name: pubsub-publisher
      image: gcr.io/containers-test-335600/pubsub-publisher
      env:
        - name: PROJECT_ID
          value: containers-test-335600
        - name: PUBSUB_TOPIC
          value: sample-topic
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /home/yone_yoshio/credential.json
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /home/root
          name: credential
---
apiVersion: v1
kind: Service
metadata:
  name: pubsub-publisher
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
