apiVersion: v1
kind: Pod
metadata:
  name: pubsub-publisher-no-credential
  labels:
    app: web
spec:
  containers:
    - name: pubsub-publisher
      image: gcr.io/containers-test-335600/pubsub-publisher
      env:
        - name: PROJECT_ID
          value: containers-test-335600
        - name: PUBSUB_TOPIC
          value: sample-topic
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pubsub-publisher
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
